### ISSUE TITLE
Missing logout button

### ISSUE THREAD

**Issue by nerrehmit** [puzzle/marina-gui#5]
Hi

Under the employee username in the top right hand corner there is no menu/ option to log out.

For an application with sensitive data as this (salary) I would like to have a logout button.

**Comment by guggero** [comment]
The reason why we first didn't add a logout button was, because it is an application in a Single Sign On realm. So logging out would mean logging out of all applications that use SSO.

But I personally agree that it would be nice to be able to log out. So I added the logout button with the text "Logout (SSO)" so it should be more or less clear the user logs out of the whole SSO realm.

Fixed by f8de7e9

**Comment by nerrehmit** [comment]
The logout button is now there but using it gives me a generic error:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Aug 09 07:47:11 UTC 2018
There was an unexpected error (type=Not Found, status=404).
No message available
